### Generate the file here
name: Catalog Service

on:
    push:
        paths:
            - 'catalog-service/**'
        branches:
            - '**'
#    pull_request:
#        branches:
#            - main
#    workflow_dispatch:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        env:
          working-directory: ./catalog-service
        defaults:
            run:
                working-directory: ${{ env.working-directory }}
        steps:
            - uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'
                  cache: 'maven'

            - name: Build with Maven
              run: ./mvnw -ntp clean verify